# permissions for end users to view shipwrightbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: shipwrightbuild-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shipwright-operator
    app.kubernetes.io/part-of: shipwright-operator
    app.kubernetes.io/managed-by: kustomize
  name: shipwrightbuild-viewer-role
rules:
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.shipwright.io
  resources:
  - shipwrightbuilds/status
  verbs:
  - get
